skip coverage on windows

diff --git a/.github/workflows/tests_matlab.yml b/.github/workflows/tests_matlab.yml
--- a/.github/workflows/tests_matlab.yml
+++ b/.github/workflows/tests_matlab.yml
@@ -120,16 +120,21 @@ jobs:
         command: cd(fullfile(getenv('GITHUB_WORKSPACE'), '.github', 'workflows')); run tests_matlab;
 
     - name: Check unit tests
-      if: matrix.test_type == 'unit'
+      if: matrix.test_type == 'unit' && ( matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' )
+      run: grep -q 0 test_report.log || { echo "Some tests failed. Check the 'Run tests' step to know which ones." >&2; exit 1; }
+    - name: Check logs windows
+      if: matrix.test_type == 'unit' && matrix.os == 'windows-latest'
       run: |
-        cat test_report.log | grep 0
+        if (-not (Get-Content test_report.log | Select-String -Pattern "0")) {
+          throw "Some tests failed.  Check the 'Run tests' step to know which ones."
+        }
 
     - name: Code coverage matlab
-      if: matrix.test_type == 'unit'
+      if: matrix.test_type == 'unit' && ( matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest' )
       uses: codecov/codecov-action@v3
       with:
         file: coverage.xml
-        flags: matlab
+        flags: ${{ matrix.os }}_matlab-${{ matrix.version }}
         name: codecov-matlab
         fail_ci_if_error: false
       # token: ${{ secrets.CODECOV_TOKEN }}  # not required but might help API rate limits
